spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: test-route
              uri: http://localhost:9090
              predicates:
                - Path=/testpath
          httpserver:
            wiretap: true
management:
  endpoints:
    web:
      exposure:
        include: gateway
# the actuator endpoint for gateway should be auto enabled but not? hence this. maybe check why
  endpoint:
    gateway:
      access: read-only
